### ISSUE TITLE
There's an issues in Hset,How to Expire?

### ISSUE THREAD

**Issue by hongxufeng** [go-redis/redis#677] opened 2017-12-06 09:19 UTC
First I set the key'expire , RedisCache.Expire(key,duration).  Later,I Hset the data ,  RedisCache.HSet(key,slavekey,value).  But  the data  never expire.  but I want it expire, please tell me how to Implement，   Thank very much;

best wishes!

**Comment by vmihailenco** [comment] 2017-12-06 10:09
Closing as duplicate of https://github.com/go-redis/redis/issues/676

**Closed by vmihailenco** 2017-12-06 10:09 UTC
