### ISSUE TITLE
V8 performance degradation ~20%

### ISSUE THREAD

**Issue by jfjm2018** [go-redis/redis#1701] opened 2021-03-17 18:47 UTC
@monkey92t 

Hi, thank you for your tests. I ran your tests in our environment, and saw similar comparative results. However, when I slightly modified the tests to reflect more accurately of our use case (and how Go HTTP spawn goroutine for each request), all the sudden the performance is degraded for V8. This is especially evident with 100+ concurrency.

2 changes that were made:
1. instead of pre-spawn Go routine and run fixed number of Get/Set in a for loop (this is retained using get2/set2), it runs through fixed number of requests and spawn a Go routine (only up to currency) to process them.
2. each request will generate a random key so the load is spread across the Redis cluster.

Both V7/V8 saw a decrease in throughput comparing using pre-spawn Go routines vs a Go routine per request. However, decrease for V7 is very small as expected, but V8 is quite dramatic.

go-redis version: v7.4.0 and v8.6.0

redis-cluster (version 5.0.7):
master: 84 instances
slave: 84 instances

This is the RedisCluster test result: [https://github.com/go-redis/redis/files/6158805/Results.pdf](https://github.com/go-redis/redis/files/6158805/Results.pdf)

This is the test program: [https://github.com/go-redis/redis/files/6158824/perftest.go.gz](https://github.com/go-redis/redis/files/6158824/perftest.go.gz)

**Comment by monkey92t** [comment] 2021-03-18 10:12
@jfjm2018  Thanks for your testing, I will try to track the work of v8.

The reason for this phenomenon, I suspect that v8 may start more goroutins, and runtime needs more time to schedule.
or... have more timers enabled?

we can post the survey results here.

**Comment by monkey92t** [comment] 2021-03-19 09:11
@jfjm2018 After my investigation, it was the problem of `go.opentelemetry.io`. After I deleted `go.opentelemetry.io` in v8, the performance returned to v7 standard.

**Comment by monkey92t** [comment] 2021-03-19 09:19
pprof v7: https://raw.githubusercontent.com/monkey92t/tool/5c568624b81168d3d080b75513484a39e3216baf/pprof_v7.svg

pprof v8: https://raw.githubusercontent.com/monkey92t/tool/5c568624b81168d3d080b75513484a39e3216baf/pprof_v8_trace.svg

pprof v8 delete trace: https://raw.githubusercontent.com/monkey92t/tool/5c568624b81168d3d080b75513484a39e3216baf/pprof_v8_delete_trace.svg


@vmihailenco  Maybe we should make `go.opentelemetry.io/otel/trace` optional?

**Comment by vmihailenco** [comment] 2021-03-19 11:56
>Maybe we should make go.opentelemetry.io/otel/trace optional?

It is already optional in the sense that it is not enabled by default. The bits we have are mainly to instrument read/write operations which can't be done outside of the core.

Is there a way to reproduce this reliably using Go benchmarks? I've tried `BenchmarkRedisPing` with and without OpenTelemetry instrumentation and the results are the same... The branch I've used is fix/no-otel.

I am running uptrace.dev with all instrumentations available and OpenTelemetry does not come at top in profiles. it is not slow at all (at least with my workload)... I guess it makes sense to benchmark OpenTelemetry API with block profile to see maybe it is slow when there are many cores...

**Comment by vmihailenco** [comment] 2021-03-19 12:17
>pprof v7: https://raw.githubusercontent.com/monkey92t/tool/5c568624b81168d3d080b75513484a39e3216baf/pprof_v7.svg

>pprof v8: https://raw.githubusercontent.com/monkey92t/tool/5c568624b81168d3d080b75513484a39e3216baf/pprof_v8_trace.svg

@monkey92t profile seems to be cut off from the bottom... and I can't sport what is making the difference...

**Comment by vmihailenco** [comment] 2021-03-19 12:36
I've sent https://github.com/open-telemetry/opentelemetry-go/pull/1717 which improves performance when OpenTelemetry is disabled. Not sure if it fixes the problem but it demonstrates that there is some room for improvement.

**Comment by monkey92t** [comment] 2021-03-19 12:39
I don't understand the work of `go.opentelemetry.io`. It should do some work by default. The phenomenon I observed has a lot of stack traces at runtime (I'm not sure), which causes ConnPool.waitTurn() to work slowly.

pprof can be downloaded to the local view
https://github.com/monkey92t/tool/blob/master/pprof_v7.svg
https://github.com/monkey92t/tool/blob/master/pprof_v8_trace.svg
https://github.com/monkey92t/tool/blob/master/pprof_v8_delete_trace.svg

After I removed go.opentelemetry.io in v8, runtime eased a lot of work.

**Comment by monkey92t** [comment] 2021-03-19 13:03
I simulated the environment on the company's imac device today. I regret that I didn't copy it to the macbook.

The results of my test are consistent with the description of this issue. In multiple goroutins, the performance drops significantly. The more goroutins, the more severe the performance drops. After tracking pprof, I found that runtime consumes a lot of CPU for stack work.

`ConnPool.waitTurn()`->`runtime.lock2`->`runtime.newstack`.

**Comment by vmihailenco** [comment] 2021-03-19 13:04
@monkey92t could you try to re-run the v8 benchmark with these lines in go.mod?

```
replace go.opentelemetry.io/otel => github.com/vmihailenco/opentelemetry-go v0.4.4-0.20210319122533-10180fd03b02

replace go.opentelemetry.io/otel/trace => github.com/vmihailenco/opentelemetry-go/trace v0.0.0-20210319122533-10180fd03b02
```

**Comment by monkey92t** [comment] 2021-03-19 13:56
> @monkey92t could you try to re-run the v8 benchmark with these lines in go.mod?
> 
> ```
> replace go.opentelemetry.io/otel => github.com/vmihailenco/opentelemetry-go v0.4.4-0.20210319122533-10180fd03b02
> 
> replace go.opentelemetry.io/otel/trace => github.com/vmihailenco/opentelemetry-go/trace v0.0.0-20210319122533-10180fd03b02
> ```

no, It seems to have no effect....

**Comment by monkey92t** [comment] 2021-03-19 15:38
@vmihailenco 

I traced the memory stack data and call chain in more detail, and found that trace.Span is irrelevant. 
I am sorry to let you test the performance of trace.Span.

But it is related to the no.2 parameter of the fn() function. I set the no.2 parameter of the fn() function to net.Conn=nil, or delete all the parameters of fn(), the same performance is low:

```go
Low: `func WithSpan(ctx context.Context, name string, fn func(context.Context, trace.Span) error) error {`

Low: `func WithSpan(ctx context.Context, name string, fn func(context.Context, net.Conn) error) error {`

Low: `func WithSpan(ctx context.Context, name string, fn func() error) error {`

Higt: `func WithSpan(ctx context.Context, name string, fn func(context.Context) error) error {`
```

The fn function must have only one parameter, the performance is the highest (I did not test 3 parameters or more), I don't understand why, I guess it is related to runtime calls? I do not really understand.

**Comment by monkey92t** [comment] 2021-03-19 15:41
@vmihailenco  At first, I found that delete `trace.Span` can restore the performance of v7, which made me mistakenly thought it was a problem with trace.Span. I'm very sorry.

**Comment by monkey92t** [comment] 2021-03-19 15:43
Maybe we should do more tests or understand the operating principle of runtime to find the answer.

**Comment by monkey92t** [comment] 2021-03-19 15:49
@vmihailenco 

My test environment:：

redis-server version: 6.2.1
redis cluster(3 master + 3 slave):
```go
127.0.0.1:1001> cluster nodes
0d59ad58465c28ef8d9da9cf83e546493251ae39 127.0.0.1:1001@11001 myself,master - 0 1616168796000 1 connected 0-4999
84bd742bcd269c774c74c738209ebf9927ac1f85 127.0.0.1:2001@12001 slave 0d59ad58465c28ef8d9da9cf83e546493251ae39 0 1616168795605 1 connected
7dc30dcbfe5ca52feb8d23be1f1efd7f8d0c76f3 127.0.0.1:2002@12002 slave 18e1d3a194fb6a5247bd46b415deb8ddade1c7ed 0 1616168797000 2 connected
18e1d3a194fb6a5247bd46b415deb8ddade1c7ed 127.0.0.1:1002@11002 master - 0 1616168797607 2 connected 5000-9999
ee9af5de66b290382cabc80a028f7d58b357e623 127.0.0.1:2003@12003 slave 47cbc60266237ed689ea11d9c6840f6995ae0e5c 0 1616168796000 5 connected
47cbc60266237ed689ea11d9c6840f6995ae0e5c 127.0.0.1:1003@11003 master - 0 1616168796606 5 connected 10000-16383
```

Run the test code of @jfjm2018 :  https://github.com/go-redis/redis/files/6158824/perftest.go.gz

**Comment by vmihailenco** [comment] 2021-03-20 07:08
Looking at https://github.com/go-redis/redis/files/6158805/Results.pdf I see that v7 is sometimes faster and sometimes v8 is faster. Sometimes performance is equal. Am I misreading the results?

**Comment by monkey92t** [comment] 2021-03-20 07:23
The performance of `set` and `get` v8 is lower.
`set2` and `get2`  v7 and v8 are similar.

According to the results, it can be seen that under the test (`set` and `get`) where goroutinue is created every time, there are problems with v8 (for example, http service creates gouroutinue every time). 

The number of goroutins has been stable (`set2` and `get2`), and there is no problem with v8.


<img width="501" alt="ebf7d37f01498e6dcbc5b1d59" src="https://user-images.githubusercontent.com/23448594/111862409-2a207c00-8990-11eb-9482-e4a7d8c2a2ba.png">

**Comment by monkey92t** [comment] 2021-03-20 07:29
If I remove `trace.Span`, the results of set and get v7 and v8 are similar.
```go
func WithSpan(ctx context.Context, name string, fn func(context.Context, trace.Span) error) error {
```
to:
```go
func WithSpan(ctx context.Context, name string, fn func(context.Context) error) error {
```

I tried to replace `trace.Span` with other interface, such as `net.Conn`, the problem still exists:
```go
func WithSpan(ctx context.Context, name string, fn func(context.Context, net.Conn) error) error {
```

**Comment by vmihailenco** [comment] 2021-03-20 09:41
I've added a benchmark in https://github.com/go-redis/redis/commit/7c5bbc37bddafa4949161febd743b9cfa8d62f5e that can be run with

```
go test -run=NONE -bench=BenchmarkSetGoroutines -benchtime=30s
```

The OpenTelemetry part is optimized in https://github.com/go-redis/redis/commit/1b77706c0c528b8c5dfd954380fe9a0fa8065677. That recovers at least some performance (according to the benchmark).

It is hard to work with the original program, because it takes too much time and results are poorly formatted.

>I tried to replace trace.Span with other interface, such as net.Conn, the problem still exists:

There is a problem, but I believe CPU profile doesn't (can't) show where it is.

**Comment by jfjm2018** [comment] 2021-03-20 16:47
You can change the plan to speed up the test

```
	planP := []int{10}                       // Pool size
	planC := []int{200}                      // Concurrency
	planM := []func(int, int, int){set, get} // Method
```

**Comment by monkey92t** [comment] 2021-03-22 03:00
> I've added a benchmark in [7c5bbc3](https://github.com/go-redis/redis/commit/7c5bbc37bddafa4949161febd743b9cfa8d62f5e) that can be run with
> 
> ```
> go test -run=NONE -bench=BenchmarkSetGoroutines -benchtime=30s
> ```
> 
> The OpenTelemetry part is optimized in [1b77706](https://github.com/go-redis/redis/commit/1b77706c0c528b8c5dfd954380fe9a0fa8065677). That recovers at least some performance (according to the benchmark).
> 
> It is hard to work with the original program, because it takes too much time and results are poorly formatted.
> 
> > I tried to replace trace.Span with other interface, such as net.Conn, the problem still exists:
> 
> There is a problem, but I believe CPU profile doesn't (can't) show where it is.

@vmihailenco 

Your modification is very good, many closure functions have been cancelled.

But I think the cause of this problem is not the closure function, so your modification is ineffective (and will cause more serious performance problems).

According to the results of my tracking runtime, the cause of this problem is the expansion of the goroutine stack space. `util.go:trace.Span` caused this result, resulting in runtime.newstrck -> runtime.copystack -> runtime.gentraceback -> ....

If the number of gouroutines is stable, it will not change after expansion, so there will be no performance problems (set2 and get2). If the gouroutine is newly created every time (set and get), it will have expansion problems every time.

In your modification, change to StartSpan and span.End(), which will cause more stack space.

I think we can not deal with this problem for the time being, but we should shorten the go-redis function call relationship.

What do you think?

**Comment by vmihailenco** [comment] 2021-03-22 07:26
>But I think the cause of this problem is not the closure function, so your modification is ineffective (and will cause more serious performance problems).

I agree that closure function is not the problem (at least benchmarks don't show anything). I've kept that change mainly because it makes the code cleaner and simpler.

But I believe other changes made some difference. E.g. on master

```
go test -run=NONE -bench=BenchmarkSetGoroutines -benchtime=30s
goos: linux
goarch: amd64
pkg: github.com/go-redis/redis/v8
cpu: AMD Ryzen 5 2600 Six-Core Processor            
BenchmarkSetGoroutines-12    	    3898	   8983290 ns/op
```

and 7c5bbc37bddafa4949161febd743b9cfa8d62f5e

```
BenchmarkSetGoroutines-12    	    3796	   9468970 ns/op
```

>If the number of gouroutines is stable, it will not change after expansion, so there will be no performance problems (set2 and get2). If the gouroutine is newly created every time (set and get), it will have expansion problems every time.

It makes sense, but this is beyond my understanding of Go runtime. I can only add that `Span` is an empty struct that is passed as an `interface{}`.

>I think we can not deal with this problem for the time being, but we should shorten the go-redis function call relationship.

Not sure what you mean by this, but I am open to suggestions. I think the first step forward is to write more small benchmarks like BenchmarkSetGoroutines so we have a relatively fast way to experiment (assuming BenchmarkSetGoroutines is not good enough). And not using ClusterClient makes everything faster/easier to run.

**Comment by monkey92t** [comment] 2021-03-22 08:20
> Not sure what you mean by this, but I am open to suggestions. I think the first step forward is to write more small benchmarks like BenchmarkSetGoroutines so we have a relatively fast way to experiment (assuming BenchmarkSetGoroutines is not good enough). And not using ClusterClient makes everything faster/easier to run.

My opinion is: At present, we cannot solve this problem because it is caused by the characteristics of golang.

The `runtime` will determine whether it needs to increase the stack space before calling the function. If necessary, it will create a new stack space and copy the old stack data over, which increases the overhead of `runtime` operation. 

This work is done by `runtime.newstrck`, `runtime.copystack` and `runtime.gentraceback`, so we see in `pprof/profile` that they take up a lot of cpu.

This principle is similar to go-slice.

Therefore, we have no better solution to this problem. We can only minimize the space occupied by the function and try to avoid stack expansion.

Or, make a radical improvement to go-redis:

```go
// Old NewClient:  client->NewClient->NewConnPool(size)->return *Client
// Old Cmd: client->cmd->hook->process->getConn->send cmd->return cmd result

// Improve NewClient: client->NewClient->NewGoroutinePool(opt.PoolSize)->return *Client
// Improve Cmd: client->cmd->send cmd chan->wait ..->return cmd result

//ExampleCode:
func NewClient(opt *Option) *Client {
        for i := 0; i < opt.PoolSize; i++ {
                go func(){
                        var conn *Conn
                        select {
                        case cmd := <-cmdChan:
                                if conn == nil || conn.isStale() {
                                        conn = opt.DialConn(addr)
                                }
                                conn.writeCmd(cmd)
                                response := conn.read()
                                cmdResultChan <- response
                        }
                }()
        }
}
func Get(ctx context.Context, key string) *StringCmd {
        cmd := NewStringCmd{}
        cmdChan <- cmd
        val := <- cmdResultChan
        return val
}


client := NewClient(opt)
val := client.Get(ctx, "key").Val()
```
In this way, go-redis has a stable number of goroutines to execute redis-cmd, which will not cause the impact of stack expansion. Although this problem can be solved, I think it is not a good idea.
Moreover, this modification requires a lot of work and takes a long time.

**Comment by monkey92t** [comment] 2021-03-22 08:34
> I think the first step forward is to write more small benchmarks like BenchmarkSetGoroutines so we have a relatively fast way to experiment (assuming BenchmarkSetGoroutines is not good enough).

We can try to write a tool to calculate the stack space required by go-redis to run.

**Comment by monkey92t** [comment] 2021-03-22 08:47
> > I think the first step forward is to write more small benchmarks like BenchmarkSetGoroutines so we have a relatively fast way to experiment (assuming BenchmarkSetGoroutines is not good enough).
> 
> We can try to write a tool to calculate the stack space required by go-redis to run. which can provide indicators for optimization

This does not seem to be a good way, we cannot confirm the size of the redis command and return value

**Comment by monkey92t** [comment] 2021-03-22 08:49
> But I believe other changes made some difference. E.g. on master
> 
> ```
> go test -run=NONE -bench=BenchmarkSetGoroutines -benchtime=30s
> goos: linux
> goarch: amd64
> pkg: github.com/go-redis/redis/v8
> cpu: AMD Ryzen 5 2600 Six-Core Processor            
> BenchmarkSetGoroutines-12    	    3898	   8983290 ns/op
> ```
> 
> and [7c5bbc3](https://github.com/go-redis/redis/commit/7c5bbc37bddafa4949161febd743b9cfa8d62f5e)
> 
> ```
> BenchmarkSetGoroutines-12    	    3796	   9468970 ns/op
> ```

After testing, I found that the modification performance of the master branch has dropped compared to v8.

**Comment by monkey92t** [comment] 2021-03-23 15:35
We should close this problem, it is not caused by go-redis, it is a golang feature

**Comment by vmihailenco** [comment] 2021-03-24 06:59
It is indeed a Go peculiarity which we could workaround if we knew more about Go runtime. I am going to close this issue mainly because it is long and there is no clear course of action (and a lot of confusion instead). If someone feels like it feel free to open a new one with the compilation of the discussion here.

I can only repeat that we need a better/more benchmarks in order to try to improve current performance. It is okay to submit custom programs as benchmarks too, but the results should be properly formatted and reasonably fast to run. For example, see https://github.com/vmihailenco/go-cache-benchmark I've written recently. That significantly improves chances that someone will jump on the issue and fix it.

**Closed by vmihailenco** 2021-03-24 06:59 UTC

**Comment by vmihailenco** [comment] 2021-03-24 07:00
>In this way, go-redis has a stable number of goroutines to execute redis-cmd, which will not cause the impact of stack expansion. >Although this problem can be solved, I think it is not a good idea.
>Moreover, this modification requires a lot of work and takes a long time.

Agreed on all points. I believe there are already clients like that and it is not always win-win situation.
