### ISSUE TITLE
Publish / Subscribe for ClusterClient

### ISSUE THREAD

**Issue by tidwall** [go-redis/redis#141] opened 2015-07-31 02:53 UTC
Is there currently a way to subscribe to a cluster? The Publish / Subscribe methods are not exposed to the ClusterClient.

The spec (http://redis.io/topics/cluster-spec) says...

"In a Redis Cluster clients can subscribe to every node, and can also publish to every other node. The cluster will make sure that published messages are forwarded as needed."

The workaround that I see at the moment is to call `client.ClusterNodes()` and parse for a random master, then create a standard client and subscribe.  This is fine, but it would finer to be able to have this done in the background.

Thanks for this tremendous project.

**Comment by noblehng** [comment] 2015-10-26 04:50
Is there a reason that the fix doesn't get merged to master?

**Comment by vmihailenco** [comment] 2015-10-26 10:24
Because publish/subscribe is non-reliable in Redis Cluster by design, see https://github.com/antirez/redis/issues/2740. To mitigate we need to slightly refactor our Redis Cluster implementation.

**Comment by noblehng** [comment] 2015-10-26 11:02
Thank you for your answer.

**Comment by danielfbm** [comment] 2017-07-01 12:37
any progress on this issue?

**Closed** 2017-07-11 08:28 UTC

**Comment by vmihailenco** [comment] 2017-07-11 16:46
@danielfbm it should be available in v6.5.3 - please try when you have a chance.

**Comment by danielfbm** [comment] 2017-07-17 07:55
thanks
