### ISSUE TITLE
parse error when using pipeline

### ISSUE THREAD

**Issue by hailangdoudou** [go-redis/redis#629] opened 2017-08-30 07:03 UTC
hi, when using pipeline, I got this error:
`redis: can't parse string reply: ":-2"`

The pipeline contains several 'Get' and 'TTL' cmd,  and this error arises occasionally.

It seems that the 'Get' cmd response is actually get the value of 'TTL'.

I wonder why this happened, and is there a possibility that pipeline returns success and the response is actually out-of-order。

**Comment by vmihailenco** [comment] 2017-08-30 07:24
It would be helpful if you could write a small program that reproduces the issue, because Pipeline code did not change for a while and I did not see any bug reports about it. So it must something very specific...

**Comment by collinmsn** [comment] 2017-08-31 06:14
Hi vmihailenco, I think there are two problems in pipeline processing, exactly in function pipelineReadCmds:

1. process should stop on any network error, such as timeout
2. non network error returned by cmd.readReply(cn) should not be taken for pipeline's error, instead, it's cmd's error only

**Comment by vmihailenco** [comment] 2017-09-01 12:10
@collinmsn I did something like you described and released v6.6.0. Hopefully it fixes this issue.

**Comment by collinmsn** [comment] 2017-09-01 12:47
It's really a nice fix, thank you.

**Comment by vmihailenco** [comment] 2017-09-11 05:53
Closing, please reopen if it happens again

**Closed by vmihailenco** 2017-09-11 05:53 UTC
