### ISSUE TITLE
Pool rate limit should only trigger on dial errors

### ISSUE THREAD

**Issue by dim** [go-redis/redis#222] opened 2015-12-21 14:20 UTC
Hi, before I submit a PR, I wanted to discuss this first. One of our apps uses redis cluster and periodically throws a series of `redis: you open connections too fast (last error: nil)` errors for no obvious reason. The affected shards seem to be stable and last error is always `nil`. I tried to debug this several times but it is only happening at a very high frequency and I can't pin it down.

Happy to hear more debug ideas, but the most obvious one is: should we really limit new connections, or should we rather limit connection failures. Assuming dial is not failing, do we need to limit? Is there another use case?

**Comment by vmihailenco** [comment] 2015-12-21 16:23
Technically rate limiting only on dial errors is fine, but it does not fix the root cause (opening/closing connections).

I suggest we improve the error message to say something like this: `redis: you open connections too fast (last_dial_error: %q last_error: %q)`, where `last_error` says why last connection was closed. I will send a PR.

**Comment by vmihailenco** [comment] 2016-04-06 11:10
I hope this is not needed any more, so closing.

**Closed by vmihailenco** 2016-04-06 11:10 UTC
