### ISSUE TITLE
Error discarding bad PubSub connection but my connection so far is good

### ISSUE THREAD

**Issue by fajardm** [go-redis/redis#1552] opened 2020-11-03 13:50 UTC
Hello everyone, my code like this
```
func TestPubsubb(T *testing.T) {
    ctx := context.Background()
    rdb := redis.NewClient(&redis.Options{
        Addr: "localhost:6379",
    })
    pubsub := rdb.Subscribe(ctx, "mychannel1")

    // Wait for confirmation that subscription is created before publishing anything.
    _, err := pubsub.Receive(ctx)
    if err != nil {
        panic(err)
    }

    // Go channel which receives messages.
    ch := pubsub.Channel()

    go func(ch <-chan *redis.Message) {
        // Consume messages.
        for msg := range ch {
            fmt.Println(msg.Channel, msg.Payload)
        }
    }(ch)

    for n := 0; n < 1000; n++ {
        // Publish a message.
        err = rdb.Publish(ctx, "mychannel1", n).Err()
        if err != nil {
            panic(err)
        }
    }
}
```

When I run `go test -v`, I got error like this
```redis: 2020/11/03 20:23:01 pubsub.go:168: redis: discarding bad PubSub connection: set tcp 127.0.0.1:38874: use of closed network connection```

The error appears in the top / middle line on my console because of println

do you have a solution?

**Comment by pierrre** [comment] 2020-12-15 14:43
probably a duplicate of https://github.com/go-redis/redis/issues/1518

**Comment by vmihailenco** [comment] 2020-12-16 08:16
You need to close the client and wait until `ch` is closed to consume all messages. Right now your app exits immediately after all messages are published but not consumed.

**Closed by vmihailenco** 2020-12-16 08:16 UTC
