### ISSUE TITLE
cannot find package "github.com/go-redis/redis/v7" 

### ISSUE THREAD

**Issue by neakni** [go-redis/redis#1177] opened 2019-10-15 09:16 UTC
go get -u github.com/go-redis/redis/v7
package github.com/go-redis/redis/v7: cannot find package "github.com/go-redis/redis/v7" in any of:

**Comment by quynhdang-vt** [comment] 2019-10-20 00:26
I got the same problem in which my go app inadvertently pick up the latest in master, and thus keep getting this error duing building:  
```
vendor/github.com/go-redis/redis/cluster.go:16:2: cannot find package "github.com/go-redis/redis/v7/internal" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal (from $GOPATH)
vendor/github.com/go-redis/redis/ring.go:14:2: cannot find package "github.com/go-redis/redis/v7/internal/consistenthash" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal/consistenthash (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOPATH)
vendor/github.com/go-redis/redis/cluster.go:17:2: cannot find package "github.com/go-redis/redis/v7/internal/hashtag" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal/hashtag (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOPATH)
vendor/github.com/go-redis/redis/cluster.go:18:2: cannot find package "github.com/go-redis/redis/v7/internal/pool" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal/pool (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal/pool (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal/pool (from $GOPATH)
vendor/github.com/go-redis/redis/cluster.go:19:2: cannot find package "github.com/go-redis/redis/v7/internal/proto" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal/proto (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal/proto (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal/proto (from $GOPATH)
vendor/github.com/go-redis/redis/command.go:12:2: cannot find package "github.com/go-redis/redis/v7/internal/util" in any of:
    /go/src/github.com/veritone/engine-toolkit/engine/vendor/github.com/go-redis/redis/v7/internal/util (vendor tree)
    /usr/local/go/src/github.com/go-redis/redis/v7/internal/util (from $GOROOT)
    /go/src/github.com/go-redis/redis/v7/internal/util (from $GOPATH)
```

Tag `v7` is not created yet for the repo?

**Comment by vmihailenco** [comment] 2019-10-21 06:43
Duplicate of https://github.com/go-redis/redis/issues/1174

**Closed by vmihailenco** 2019-10-21 06:43 UTC
