### ISSUE TITLE
high memory usage + solution

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#832] opened 2018-08-03 12:55 UTC
Hi,

I noticed that the memory usage was very high in my project.
I did a memory profiling with `inuse_space`, and 90% of my memory is used by `go-redis` in `WriteBuffer`.
If I understand correctly, each connection in the pool has its own `WriteBuffer`.

My projects runs 80 goroutines (on 8 CPUs) and each goroutine `SET` Redis keys.
My Redis keys are large: several MB. (less than 100 MB)
So, it's very easy to understand why the memory usage is very high.

I think I have a solution, but it requires changes in `go-redis` internals.
We could use a global `sync.Pool` of `WriteBuffer` instead.

WDYT ?

**Comment by pierrre** [comment] 2018-08-03 14:01
Here is a quick POC:
```diff
diff --git a/vendor/github.com/go-redis/redis/command.go b/vendor/github.com/go-redis/redis/command.go
index 992e614..4509a34 100644
--- a/vendor/github.com/go-redis/redis/command.go
+++ b/vendor/github.com/go-redis/redis/command.go
@@ -46,14 +46,15 @@ func firstCmdsErr(cmds []Cmder) error {
 }
 
 func writeCmd(cn *pool.Conn, cmds ...Cmder) error {
-	cn.Wb.Reset()
+	wb := proto.GetWriteBufferPool()
+	defer proto.PutWriteBufferPool(wb)
 	for _, cmd := range cmds {
-		if err := cn.Wb.Append(cmd.Args()); err != nil {
+		if err := wb.Append(cmd.Args()); err != nil {
 			return err
 		}
 	}
 
-	_, err := cn.Write(cn.Wb.Bytes())
+	_, err := cn.Write(wb.Bytes())
 	return err
 }
 
diff --git a/vendor/github.com/go-redis/redis/internal/pool/conn.go b/vendor/github.com/go-redis/redis/internal/pool/conn.go
index acaf366..13ef043 100644
--- a/vendor/github.com/go-redis/redis/internal/pool/conn.go
+++ b/vendor/github.com/go-redis/redis/internal/pool/conn.go
@@ -14,7 +14,6 @@ type Conn struct {
 	netConn net.Conn
 
 	Rd *proto.Reader
-	Wb *proto.WriteBuffer
 
 	Inited bool
 	usedAt atomic.Value
@@ -23,7 +22,6 @@ type Conn struct {
 func NewConn(netConn net.Conn) *Conn {
 	cn := &Conn{
 		netConn: netConn,
-		Wb:      proto.NewWriteBuffer(),
 	}
 	cn.Rd = proto.NewReader(cn.netConn)
 	cn.SetUsedAt(time.Now())
diff --git a/vendor/github.com/go-redis/redis/internal/proto/write_buffer.go b/vendor/github.com/go-redis/redis/internal/proto/write_buffer.go
index 664f4c3..a7ebbce 100644
--- a/vendor/github.com/go-redis/redis/internal/proto/write_buffer.go
+++ b/vendor/github.com/go-redis/redis/internal/proto/write_buffer.go
@@ -4,6 +4,7 @@ import (
 	"encoding"
 	"fmt"
 	"strconv"
+	"sync"
 )
 
 type WriteBuffer struct {
@@ -111,3 +112,19 @@ func formatUint(u uint64) string {
 func formatFloat(f float64) string {
 	return strconv.FormatFloat(f, 'f', -1, 64)
 }
+
+var writeBufferPool = &sync.Pool{
+	New: func() interface{} {
+		return NewWriteBuffer()
+	},
+}
+
+func GetWriteBufferPool() *WriteBuffer {
+	w := writeBufferPool.Get().(*WriteBuffer)
+	w.Reset()
+	return w
+}
+
+func PutWriteBufferPool(w *WriteBuffer) {
+	writeBufferPool.Put(w)
+}
```

**Comment by vmihailenco** [comment] 2018-08-03 14:51
Hi,

>I noticed that the memory usage was very high in my project.

How much memory is used by go-redis? What is the value of Options.PoolSize?

>Here is a quick POC:

Can you try it on your real workload and check how much memory is saved? I don't think it will be very useful because if you have 80 running goroutines sync.Pool will have 80 WriteBuffers and you will save nothing.

I would also try to reduce Options.PoolSize - go-redis uses large pool (10 * cpu_count) since Redis connections & RAM are cheap and having large pool can squeeze more requests  per seconds on some benchmarks.

**Comment by pierrre** [comment] 2018-08-03 15:00
> How much memory is used by go-redis?

My projects uses 3-4 GB of RAM, and the heap profiling (inuse_space) reports that 90% of the memory is used by `go-redis`.

> What is the value of Options.PoolSize?

It is currently undefined, so I think it's `10 * CPUs`, on my server it's 10 * 8 = 80.

> Can you try it on your real workload and check how much memory is saved?

I will try next week.

> I would also try to reduce Options.PoolSize

Yes, I thought about that. I will also try next week.

**Comment by vmihailenco** [comment] 2018-08-03 15:42
>I will try next week.

Thanks. If you need quick fix lowering PoolSize should free some memory. Actually I think you need to tweak it anyway.

On go-redis side we could change connection to use same buffer for reading and writing, but that would require special fix for PubSub where reading and writing can happen at the same time.

**Comment by vmihailenco** [comment] 2018-08-12 09:04
Master branch should have lower memory usage but if you want to further lower memory usage I advice to:
- Lower Options.PoolSize.
- Try using Options.MaxConnAge which will close old connections and free associated read/write buffer. New connections will start with default buffer size and grow buffer as needed.

**Comment by pierrre** [comment] 2018-08-13 09:44
Sorry for the late reply, I couldn't test everything last week.

I tried to reduce the `PoolSize` to 8 (my default value is 8*10=80).
It didn't change much the memory usage, so I suppose I didn't reach this limit.

Today I tried the latest version of go-redis.
I upgraded from a80633d319dee5c0f45a79997ef769b86607be10 to 33287c7c34f9c180bf1ede58f725ae1469ee8888.
The memory usage was a little bit lower, but not so much.
You will see on the attached image.
I released at 9:00.

I also tried my suggestion here https://github.com/go-redis/redis/issues/832#issuecomment-410263105
I deployed a single instance with go-redis ad7024da36c335474dc6c260bc6e5dbb76b1b403 and my suggested change.
This was a huge improvement for the memory usage.

![capture du 2018-08-13 11-36-01](https://user-images.githubusercontent.com/131535/44024541-d7ec57ae-9eed-11e8-8e75-df4cbc532d4e.png)

I still think a pool of buffer is more efficient:
- it will not depend on the number of connections in the pool
- buffers in the pool are freed after a garbage collection

**Comment by pierrre** [comment] 2018-08-13 10:14
BTW, I can't use `Try using Options.MaxConnAge` because it's not available in `UniversalOptions` (my Redis client is a cluster or standalone depending on the environment)

**Comment by pierrre** [comment] 2018-08-14 12:51
Can we re-open the issue ?

**Comment by vmihailenco** [comment] 2018-08-14 13:05
I can't simply start using sync.Pool because:
- there is a connection pool and having 2nd pool for the buffer sounds suspiciously
- sync.Pool drops all buffers on each garbage collection tick which is sub-optimal/unwanted in most cases

Also I don't understand why go-redis uses 1.5gb without your patch? If you have 8 connections and your average payload is 20mb memory usage should be 8*20=160mb. Can you reproduce the problem in standalone program?

**Comment by vmihailenco** [comment] 2018-08-14 13:13
PS If some values can be really large (like 200mb) it could explain high memory usage: 8 * 200 ~ 1.5gb.

**Comment by pierrre** [comment] 2018-08-14 14:09
> there is a connection pool and having 2nd pool for the buffer sounds suspiciously

I'm not sure to understand.
We could have a pool of connections (network sockets) and a pool of buffers (allocated memory).

> sync.Pool drops all buffers on each garbage collection tick which is sub-optimal/unwanted in most cases

I'm not sure it is officially documented.
I think this is the current implementation, but it could change.

IMO, it's better to recycle the allocated memory as soon as possible.
It allows to keep the memory usage small.

I understand why each connection has its own buffer in `go-redis`.
However, if a connection is idle during several seconds, what is better ?
- keep the buffer memory allocated and unused ?
- recycle the buffer (IMO it is relatively cheap to recycle/allocate a new buffer)

> Also I don't understand why go-redis uses 1.5gb without your patch? If you have 8 connections and your average payload is 20mb memory usage should be 8*20=160mb. Can you reproduce the problem in standalone program?

Yes, I'm trying to understand too.
I'm adding debugs logs that will print the size of my keys in my app.

**Comment by vmihailenco** [comment] 2018-08-15 09:17
I've created https://github.com/go-redis/redis/pull/842 with sync.Pool used for read and write buffers. If you are able to create benchmark that shows significant improvements over master branch I will consider merging it. My attempts to write such benchmark suggest that
- we use less RAM but more CPU and overall ops/second is lower
- lowering pool size fixes RAM usage with big values and big pool

**Comment by pierrre** [comment] 2018-08-15 09:25
Thank you, I will test it tomorrow 👍 

> we use less RAM but more CPU and overall ops/second is lower

In my app, Redis is not the most CPU intensive code.
So I don't think the increase in CPU usage will affect the speed.

I agree that in a "pure Redis" benchmark, this will be slower (we need to allocate/free memory more frequently)

> lowering pool size fixes RAM usage with big values and big pool

I will try this again.
Maybe I did something wrong last time.

**Comment by pierrre** [comment] 2018-08-16 08:42
Yes, #842 is very efficient for me.
The memory usage is 50-70% lower

![capture du 2018-08-16 10-36-46](https://user-images.githubusercontent.com/131535/44198018-7bb15c00-a140-11e8-8c55-6ae1ce10ecdd.png)

My CPU usage didn't increase.
I think that in real projects, the CPU usage will not increase much.

FYI, I also use `GOGC=50`.

**Comment by vmihailenco** [comment] 2018-08-17 11:29
This should be fixed in master - memory usage should be lower & client faster.

**Closed** 2018-08-17 11:28 UTC

**Comment by pierrre** [comment] 2018-08-17 12:33
thank you @vmihailenco :+1:

**Comment by pierrre** [comment] 2018-08-17 12:35
I will try this ASAP.
Aren't you merging https://github.com/go-redis/redis/pull/842 ?
Is https://github.com/go-redis/redis/pull/844 equivalent ?

**Comment by pierrre** [comment] 2018-08-17 13:45
The code from #844 / 21826c1c21b6ed032b81b31f8cec08dbf73f4d12 doesn't improve the memory usage.
![capture du 2018-08-17 15-40-42](https://user-images.githubusercontent.com/131535/44269243-3b330a80-a234-11e8-8f27-f5590ed059f6.png)
The memory usage of my test instance quickly increases, and is equal to the other instances.
#842 was better.

FYI, my largest Redis value is 3MB.
But I can't tell you how many connections there are in the pool.
My server has 8 CPU, so I think the maximum is 80.

**Comment by vmihailenco** [comment] 2018-08-18 05:35
Okay, if you want to move this forward please create a program that reproduces the problem using latest master branch and open new issue. My tests show that memory usage was improved so I guess you have something different.

**Comment by pierrre** [comment] 2018-08-20 14:28
Today I tried the latest `master` with tweaked values for `PoolSize` and `MaxConnAge`.
It seems to work in my app, the memory usage is considerably lower.

Thank you ! :+1:

**Comment by vmihailenco** [comment] 2018-08-21 05:42
I think there is no need to tweak `MaxConnAge` any more. `PoolSize` option is still useful but it should be tuned based on benchmarks results.

**Comment by pierrre** [comment] 2018-08-21 19:02
Can you confirm `MaxConnAge` will close a connection (and free the buffer) if it is idle during more than the specified duration ?
If so, I think it is useful, because my app doesn't always use Redis.
Sometimes, it doesn't use it for 20 seconds.

**Comment by vmihailenco** [comment] 2018-08-22 06:12
No, that is what IdleTimeout does. See https://github.com/go-redis/redis/blob/master/options.go#L65-L80 and let me know if anything needs refinement.

**Comment by pierrre** [comment] 2018-09-20 15:49
This issue is very similar https://github.com/golang/go/issues/23199 (even if `sync.Pool` is not used in `go-redis`).
There is a kind of memory leak if a buffer grows to a very large size, then is recycled and used for only very small values.

If I understand correctly, the proposed solution is to not recycle buffers if they are larger than 64 KiB.
See the CL mentioned in the comments.
