### ISSUE TITLE
TotalConns < IdleConns by large amount.

### ISSUE THREAD

**Issue by cep21** [go-redis/redis#1059] opened 2019-06-16 18:02 UTC
Version: 6.15.3

The documentation for `IdleConns` and `TotalConns` implies that idle connections are a subset of total connections, but our statistics of the clustered client show that idle connections are on the order of 2,600 and total connections are around 800.  How can idle connections be much higher than the total connections?

**Comment by cep21** [comment] 2019-06-16 18:10
If I'm misunderstanding the documentation, we can update it.  But if it's not possible for IdleConns to be so much higher than TotalConns, there's possibly a bug in how this is tracked and maybe some instrumentation could help find where.

**Comment by vmihailenco** [comment] 2019-06-17 08:55
IdleConns should be <= TotalConns - docs are correct. If it is not - it is a bug. Are you able to reproduce it on simple program?

**Comment by cep21** [comment] 2019-06-18 00:05
The program is very complex.  I'll see if I can reproduce it more simply.  We send all of PoolStats() to a statsd cluster.

Here you can see that idle and total connections generally follow each other.  We had a spike of misses (these are PoolStats.misses) and idle (the green line) outgrew yellow (total connections)

![Screen Shot 2019-06-17 at 5 02 26 PM](https://user-images.githubusercontent.com/20358/59644502-0593d200-9122-11e9-9fd4-0b45def91f21.png)

**Comment by cep21** [comment] 2019-06-18 00:11
If I break down our metrics by hosts, rather than summing them across the tier, I can see that each host follows the same behavior: idle < total, but around the same time window they diverge and idle >> total (for each host)

**Comment by kollektiv** [comment] 2019-07-03 20:45
I'm also seeing this behavior using version 73d3c18522e8, and a ElastiCache Redis cluster client with 9 nodes

![Screen Shot 2019-07-03 at 1 43 53 PM](https://user-images.githubusercontent.com/85360/60623907-c491f380-9d98-11e9-89d3-1400c8e50227.png)

**Comment by kollektiv** [comment] 2019-08-02 16:24
Instead of having a separate counters for sizes `p.poolSize` and `p.idleConnsLen`, what if the counts are measured with `len(p.idleConns)` and `len(p.conns)` to try an eliminate any discrepancies?

**Comment by vmihailenco** [comment] 2019-08-03 13:12
This may be fixed by https://github.com/go-redis/redis/commit/6cd6cd828fa443597c911d542766c6b5a665bf49.

poolSize is needed, because it is incremented before async creating a connection so we don't over-create connections. But in PoolStats we indeed could use len(p.idleConns) and len(p.conns).

**Comment by aniketsupertramp** [comment] 2022-01-18 20:19
Hi @vmihailenco / All, 
am using v7.4.0 and i can still observe the same issue.
The total connections (as exposed by **PoolStats().TotalConns** ) is less than Idle Connections (exposed by PoolStats().IdleConns) .
total connections are around 240 per node and idle connections are around 1.4k for the same node, and this is same for all the nodes we have.

Any help, how can we resolve this?

**Comment by vmihailenco** [comment] 2022-01-20 09:57
Try to upgrade to latest version and read https://redis.uptrace.dev/guide/performance.html#large-number-of-open-connections

Closing since this is an old issue.

**Closed by vmihailenco** 2022-01-20 09:57 UTC
