### ISSUE TITLE
redis: discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by rush24** [go-redis/redis#949] opened 2019-01-09 10:01 UTC
https://github.com/go-redis/redis/issues/938#issuecomment-452209289

**Comment by vmihailenco** [comment] 2019-01-09 11:40
Please provide a program that reproduces the problem.

**Comment by rush24** [comment] 2019-01-09 12:02
That was a sporadic problem in production env, may hard to reproduce

**Comment by iproctor** [comment] 2019-01-10 16:10
I have the same issue and made this hacky fix: https://github.com/sp0n-7/redis/commit/4542feb74c96a5ab4bbad667a1aeebd5493808b4
The problem is that once !healthy, it will go immediately from c.Ping() to reconnecting without giving it 5 seconds to receive the ping response and become healthy again.

**Comment by antegulin** [comment] 2019-02-04 18:12
Any progress on this?

**Comment by vmihailenco** [comment] 2019-02-06 10:05
No, there is still no reproducers.

**Comment by antegulin** [comment] 2019-02-18 08:41
My issue was caused by not closing unnecessary subscription channels, over time there would be a bunch of open subscriptions (to the same channel), which caused this error. 
Having that said, I'm not sure why `ping timeout` would occur since the timer is set to 5s. I had a few hundred to thousands of open subscriptions, is it possible that their consecutive execution caused ping timeout to block?

**Comment by shscy** [comment] 2019-02-25 03:10
@rush24  hi, see https://github.com/go-redis/redis/blob/master/pubsub.go#L397-L422, if the `c.Receive` method blocked, the `c.ping` channel will be empty,  here https://github.com/go-redis/redis/blob/master/pubsub.go#L446-L450, the case `case <-c.ping` will never success which will results the timer timeout.

**Comment by vmihailenco** [comment] 2019-02-25 08:56
Okay, what about a simple program that reproduces the problem you described?

**Comment by button-chen** [comment] 2019-03-09 17:00
I know this bug:   pr #991

test code:
`package main

import (
	"time"

	"github.com/go-redis/redis"
)

func main() {
	redisdb := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
	})

	pubsub := redisdb.Subscribe("/test")
	_, err := pubsub.Receive()
	if err != nil {
		panic(err)
	}
	ch := pubsub.Channel()
	go func() {
		for {
			select {
			case <-ch:
				// Trigger bug: Simulating a very slow consumer
				time.Sleep(time.Second * 50)
			}
		}
	}()

	for {
		err := redisdb.Publish("/test", "testmessage").Err()
		if err != nil {
			panic(err)
		}
		time.Sleep(time.Millisecond)
	}
}

// error message output:
// discarding bad PubSub connection: redis: ping timeout
`

**Closed** 2019-03-12 11:07 UTC
