### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Justin910** [go-redis/redis#2103] opened 2022-06-01 03:38 UTC
I tried to upgrade to V8 and still Crash, Help me

![image](https://user-images.githubusercontent.com/25916027/171322698-45fc0a96-efea-4673-a514-6e7d0aa47d14.png)

**Comment by Justin910** [comment] 2022-06-01 07:40
go version: 1.13.5
system version: ubuntu1~16.04.12

**Comment by wangrzneu** [comment] 2022-06-04 04:02
Can you show me how to reproduce this issue? @Justin910

**Comment by Justin910** [comment] 2022-06-04 16:24
```
pipe := this.redisClusterConn.Pipeline()
defer pipe.Close()

ctx, _ := context.WithTimeout(context.Background(), time.Second)

for key, values := range m {

    pipe.HMSet(ctx, key, values)
    if keyExpireTime > 0 {
        pipe.Expire(ctx, key, keyExpireTime)
    }
}

_, err := pipe.Exec(ctx) 
```

```
pipe := this.redisClusterConn.Pipeline()
defer pipe.Close()

ctx, _ := context.WithTimeout(context.Background(), time.Second)

for _, key := range keys {
    pipe.HGetAll(ctx, key).Result()
}

pipeRet, err := pipe.Exec(ctx)

if err != nil {
    return nil, err
}
```

Here's the code we used. We used the get and set interfaces for hash. 
We can't reproduce it in our own tests, but when we run it in production, we occasionally get a crash situation. 
According to the crash law of the first few times, it will occur about once every few days.
@wangrzneu

**Comment by git-hulk** [comment] 2022-06-17 15:55
@Justin910 I think you can have a try at v9 which has fixed the wild pointer cause by StringToByte function: https://github.com/go-redis/redis/pull/693

**Comment by vmihailenco** [comment] 2022-06-22 07:46
Wild pointer was fixed much earlier - at least in v8, may be even earlier...

**Comment by vmihailenco** [comment] 2022-06-22 07:47
Anyway, I am closing this since there is no clear way how to reproduce this issue and the lib does not crash for most users.

**Closed by vmihailenco** 2022-06-22 07:47 UTC

**Comment by Justin910** [comment] 2022-06-22 08:26
```
package main

import (
	"context"
	"fmt"
	redis "github.com/go-redis/redis/v8"
	"os"
	"runtime"
	"time"
)

var redisconn *redis.ClusterClient

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	addrs := []string{
		"127.0.0.1:6379",
	}
	pwd := "123"

	redisconn = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:        addrs,
		Password:     pwd,
		DialTimeout:  time.Second * 1,
		ReadTimeout:  time.Second * 1,
		WriteTimeout: time.Second * 1,
		PoolSize:     1,
	})
	defer redisconn.Close()

	var str string
	go func() {
		var v string
		defer func() {
			if err1 := recover(); err1 != nil {

				m := make(map[string]map[string]interface{})
				m["test"] = map[string]interface{}{
					"test": v,
				}

				SetMaps(m, time.Second)
				os.Exit(0)
			}
		}()

		for {
			v = str
			fmt.Printf("%s\n", v)
		}
	}()

	for {
		str = ""
		time.Sleep(time.Nanosecond)
		str = "/test/test/test"
		time.Sleep(time.Nanosecond)
	}
}

func SetMaps(m map[string]map[string]interface{}, keyExpireTime time.Duration) {

	if len(m) == 0 {
		return
	}

	pipe := redisconn.Pipeline()
	defer pipe.Close()

	ctx, _ := context.WithTimeout(context.Background(), time.Second)

	for key, values := range m {
		pipe.HMSet(ctx, key, values)
		if keyExpireTime > 0 {
			pipe.Expire(ctx, key, keyExpireTime)
		}
	}

	_, err := pipe.Exec(ctx)
	if err != nil {
		fmt.Println("SetMaps Pipeline exec error:", err.Error())
	}
}

```

@vmihailenco  @git-hulk We reproduced the problem, it's not a problem with go-redis itself
